In [10]:
import pandas as pd

In [ ]:
birth_rate = pd.read_csv(r"C:/Downloads/new_data/birth_rate.csv")
eu_regions = pd.read_csv(r"C:/Downloads/new_data/eu_country.csv")
birth_rate.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,FREQ,Frequency of observation,TERRITORIAL_LEVEL,Territorial level,REF_AREA,Reference area,...,OBS_VALUE,Observation value,COUNTRY,Country,OBS_STATUS,Observation status,UNIT_MULT,Unit multiplier,DECIMALS,Decimals
0,DATAFLOW,OECD.CFE.EDS:DSD_REG_DEMO@DF_FERTILITY(2.0),Fertility - Regions,I,A,Annual,CTRY,Country,SVN,Slovenia,...,1.46,NaN,SVN,Slovenia,A,Normal value,0,Units,2,Two
1,DATAFLOW,OECD.CFE.EDS:DSD_REG_DEMO@DF_FERTILITY(2.0),Fertility - Regions,I,A,Annual,CTRY,Country,FRA,France,...,1.78,NaN,FRA,France,A,Normal value,0,Units,2,Two
2,DATAFLOW,OECD.CFE.EDS:DSD_REG_DEMO@DF_FERTILITY(2.0),Fertility - Regions,I,A,Annual,CTRY,Country,ROU,Romania,...,1.83,NaN,ROU,Romania,A,Normal value,0,Units,2,Two
3,DATAFLOW,OECD.CFE.EDS:DSD_REG_DEMO@DF_FERTILITY(2.0),Fertility - Regions,I,A,Annual,CTRY,Country,DNK,Denmark,...,1.67,NaN,DNK,Denmark,A,Normal value,0,Units,2,Two
4,DATAFLOW,OECD.CFE.EDS:DSD_REG_DEMO@DF_FERTILITY(2.0),Fertility - Regions,I,A,Annual,CTRY,Country,IDN,Indonesia,...,3.33,NaN,IDN,Indonesia,A,Normal value,0,Units,2,Two

In [12]:
birth_rate.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'ACTION', 'FREQ',
       'Frequency of observation', 'TERRITORIAL_LEVEL', 'Territorial level',
       'REF_AREA', 'Reference area', 'TERRITORIAL_TYPE',
       'Territorial typology', 'MEASURE', 'Measure', 'AGE', 'Age', 'SEX',
       'Sex', 'UNIT_MEASURE', 'Unit of measure', 'TIME_PERIOD', 'Time period',
       'OBS_VALUE', 'Observation value', 'COUNTRY', 'Country', 'OBS_STATUS',
       'Observation status', 'UNIT_MULT', 'Unit multiplier', 'DECIMALS',
       'Decimals'],
      dtype='object')

In [13]:
# kiểm tra các giá trị có thể có
birth_rate["MEASURE"].unique()

array(['FERT_RATIO'], dtype=object)

In [14]:
# chọn các cột quan trọng, đổi tên
test = birth_rate[["TIME_PERIOD","REF_AREA","Reference area","Age","OBS_VALUE"]]
test = test.rename(columns= { "Reference area" : "Country",
                      "TIME_PERIOD" : "Year",
                      "OBS_VALUE" : "FERT_RATIO"

})

In [15]:
#phân loại và lọc các giá trị phù hợp
age = test["Age"] == "Total"
test = test[age]
test["FERT_RATIO"] = test["FERT_RATIO"].dropna()
test

      Year REF_AREA     Country    Age  FERT_RATIO
0     1990      SVN    Slovenia  Total    1.460000
1     1990      FRA      France  Total    1.780000
2     1990      ROU     Romania  Total    1.830000
3     1990      DNK     Denmark  Total    1.670000
4     1990      IDN   Indonesia  Total    3.330000
...    ...      ...         ...    ...         ...
6299  2018      PRT    Portugal  Total    1.420000
6300  2019      PRT    Portugal  Total    1.430000
6301  2019      CRI  Costa Rica  Total    1.556804
6302  2020      CRI  Costa Rica  Total    1.406147
6303  2022      CRI  Costa Rica  Total    1.290000

[1300 rows x 5 columns]

In [16]:
# lọc các nước nằm trong châu âu
eu = test["Country"].isin(eu_regions["Country"])
test = test[eu]

#reset lại chỉ mục
test =test.reset_index(drop = True)

In [19]:
test.isna().any(axis=1).any().sum()

np.int64(0)

In [18]:
# test.to_csv("C:/Downloads/birth_rate_clean.csv")